### ISSUE TITLE
GLIBC_2.32' not found 

### ISSUE THREAD

**Issue by rammos92** [rust3r/btc_hex_brute#1]
./btc_hex_brute: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./btc_hex_brute)

**Comment by rammos92** [comment]
can you make a version windows

**Comment by rust3r** [comment]
Added in release [v1.0.1](https://github.com/rust3r/btc_hex_brute/releases/tag/v1.0.1)
