### ISSUE TITLE
missing WIF CHARACTERS

### ISSUE THREAD

**Issue by Handsomekaizer** [rust3r/btc_hex_brute#6]
Hello sir
Sorry to bother I was just going through your repo to see if you could help me. The problem I have is with my wallet private key characters, I mistakenly damaged the piece of paper I wrote it on, so I was wondering if you could help me write a program that will brute Force all the 10 missing characters very fast and find the correct characters and in return I will make a donation of 2 BTC to you if I find the correct keys

**Comment by rust3r** [comment]
Hello! Can we use Tox for messaging?

**Comment by An1an1** [comment]
> Здравствуйте, сэр . Извините за задержку. Я просто просмотрел репо, чтобы узнать, не могли бы вы мне помочь. У меня проблема с символами закрытого ключа моего кошелька, я заплатил повредил лист бумаги, на который его написал, поэтому мне было интересно, не могли бы вы помочь мне написать программу, которая очень быстро переборит все 10 недостающих символов и найдет нужные символы, а взамен я сделаю вам пожертвование в размере 2 BTC, если найду ключи

Вам помогли ?
